from __future__ import annotations

import random
from datetime import datetime, date
from pathlib import Path

import pandas as pd
from sqlalchemy.orm import Session

from app.core.config import get_settings
from app.models.finance_models import Budget, GoalContribution, SavingsGoal, Transaction
from app.models.investment_models import Investment, RecurringTransaction
from app.models.user_models import User, UserProfile
from app.seed.seed_defaults import seed_default_categories
from app.services.recurring_detection import rescan_recurring_for_user

settings = get_settings()

DEMO_CSV_PATH = (
    Path(__file__).resolve().parents[3]
    / "machine-learning" / "data" / "generated" / "expensecast_demo_transactions.csv"
)


def seed_demo_user(db: Session) -> User:
    """
    Creates the single, fixed fictional demo user and loads it with the
    isolated demo dataset generated by
    machine-learning/data/generate_sample_data.py --demo.
    This is fully separate from any real user account: it is the only
    place demo_user_001's user_id is ever used.
    """
    demo_user = db.get(User, settings.DEMO_USER_ID)
    if demo_user:
        return demo_user  # already seeded

    demo_user = User(
        id=settings.DEMO_USER_ID,
        email="demo@expensecast.app",
        full_name="Demo Account",
        is_demo_user=True,
    )
    db.add(demo_user)
    db.commit()

    profile = UserProfile(
        user_id=demo_user.id, user_type="salaried", preferred_currency="INR",
        approx_monthly_income=72000, budget_start_day=1, onboarding_completed=True,
    )
    db.add(profile)

    name_to_category_id = seed_default_categories(db)

    if DEMO_CSV_PATH.exists():
        df = pd.read_csv(DEMO_CSV_PATH)
        for _, row in df.iterrows():
            category_id = name_to_category_id.get(row["category"])
            db.add(Transaction(
                user_id=demo_user.id,
                date=pd.to_datetime(row["date"]).date(),
                transaction_type=row["transaction_type"],
                amount=float(row["amount"]),
                currency=row.get("currency", "INR"),
                category_id=category_id,
                description=row.get("description"),
                merchant=row.get("merchant"),
                payment_method=row.get("payment_method"),
                is_recurring=bool(row.get("is_recurring", False)),
                source="demo",
            ))
        db.commit()

    # Demo budgets
    today = date.today()
    for cat_name, limit in [("Food", 8000), ("Shopping", 6000), ("Transport", 3000), ("Entertainment", 2500)]:
        cat_id = name_to_category_id.get(cat_name)
        db.add(Budget(
            user_id=demo_user.id, category_id=cat_id, name=f"{cat_name} Budget",
            period_month=today.month, period_year=today.year, limit_amount=limit,
        ))

    # Demo savings goal
    goal = SavingsGoal(
        user_id=demo_user.id, goal_name="Emergency Fund", target_amount=100000,
        current_amount=42000, target_date=date(today.year + 1, today.month, 1),
        monthly_required_amount=4833.33,
    )
    db.add(goal)
    db.commit()
    db.refresh(goal)
    db.add(GoalContribution(goal_id=goal.goal_id, user_id=demo_user.id, amount=42000, contribution_date=today, note="Initial demo balance"))

    # Demo investments
    for name, itype, invested, current in [
        ("HDFC Flexi Cap SIP", "sip", 60000, 68500),
        ("PPF Account", "provident_fund", 150000, 165000),
        ("Gold ETF", "gold", 20000, 21800),
    ]:
        db.add(Investment(
            user_id=demo_user.id, investment_name=name, investment_type=itype,
            amount_invested=invested, investment_date=date(today.year - 1, 6, 15), current_value=current,
        ))

    db.commit()

    rescan_recurring_for_user(db, demo_user.id)
    for r in db.query(RecurringTransaction).filter(RecurringTransaction.user_id == demo_user.id).all():
        r.confirmed_by_user = True
    db.commit()

    return demo_user
